version: '3.1'

services: 
  db:
    image: mysql
    restart: always
    volumes:
      - "./.mysql/db:/var/lib/mysql"
    ports: 
     - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD:  1234
      MYSQL_DATABASE: delilah_resto